
function TRI_EN_config(this_block)

  % Revision History:
  %
  %   27-Apr-2008  (12:15 hours):
  %     Original code was machine generated by Xilinx's System Generator after parsing
  %     D:\Data\Xilinx\sysgen\SSP\ssp_proto\V2_2\TRI_EN.vhd
  %
  %

  this_block.setTopLevelLanguage('VHDL');

  this_block.setEntityName('TRI_EN');

  % System Generator has to assume that your entity  has a combinational feed through; 
  %   if it  doesn't, then comment out the following line:
  this_block.tagAsCombinational;

  this_block.addSimulinkInport('RESET');

  this_block.addSimulinkOutport('EN1');
  this_block.addSimulinkOutport('EN2');
  this_block.addSimulinkOutport('EN3');

  EN1_port = this_block.port('EN1');
  EN1_port.setType('Bool');
  EN1_port.useHDLVector(false);
  EN2_port = this_block.port('EN2');
  EN2_port.setType('Bool');
  EN2_port.useHDLVector(false);
  EN3_port = this_block.port('EN3');
  EN3_port.setType('Bool');
  EN3_port.useHDLVector(false);

  % -----------------------------
  if (this_block.inputTypesKnown)
    % do input type checking, dynamic output type and generic setup in this code block.

    if (this_block.port('RESET').width ~= 1);
      this_block.setError('Input data type for port "RESET" must have width=1.');
    end

    this_block.port('RESET').useHDLVector(false);

  end  % if(inputTypesKnown)
  % -----------------------------

  % -----------------------------
   if (this_block.inputRatesKnown)
     setup_as_single_rate(this_block,'CLK','CE')
   end  % if(inputRatesKnown)
  % -----------------------------

    % (!) Set the inout port rate to be the same as the first input 
    %     rate. Change the following code if this is untrue.
    uniqueInputRates = unique(this_block.getInputRates);


  % Add addtional source files as needed.
  %  |-------------
  %  | Add files in the order in which they should be compiled.
  %  | If two files "a.vhd" and "b.vhd" contain the entities
  %  | entity_a and entity_b, and entity_a contains a
  %  | component of type entity_b, the correct sequence of
  %  | addFile() calls would be:
  %  |    this_block.addFile('b.vhd');
  %  |    this_block.addFile('a.vhd');
  %  |-------------

  %    this_block.addFile('');
  %    this_block.addFile('');
  this_block.addFile('TRI_EN.vhd');

return;


% ------------------------------------------------------------

function setup_as_single_rate(block,clkname,cename) 
  inputRates = block.inputRates; 
  uniqueInputRates = unique(inputRates); 
  if (length(uniqueInputRates)==1 & uniqueInputRates(1)==Inf) 
    block.addError('The inputs to this block cannot all be constant.'); 
    return; 
  end 
  if (uniqueInputRates(end) == Inf) 
     hasConstantInput = true; 
     uniqueInputRates = uniqueInputRates(1:end-1); 
  end 
  if (length(uniqueInputRates) ~= 1) 
    block.addError('The inputs to this block must run at a single rate.'); 
    return; 
  end 
  theInputRate = uniqueInputRates(1); 
  for i = 1:block.numSimulinkOutports 
     block.outport(i).setRate(theInputRate); 
  end 
  block.addClkCEPair(clkname,cename,theInputRate); 
  return; 

% ------------------------------------------------------------

