-- VHDL Entity idx_fpga_lib.adc_v1_tb.symbol
--
-- Created:
--          by - nort.Domain Users (NORT-XPS14)
--          at - 16:55:43 04/07/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2013.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;



ENTITY adc_v1_tb IS
   GENERIC( 
      BASE_ADDR : std_logic_vector := X"0E80"
   );
-- Declarations

END adc_v1_tb ;

--
-- VHDL Architecture idx_fpga_lib.adc_v1_tb.struct
--
-- Created:
--          by - nort.Domain Users (NORT-XPS14)
--          at - 17:14:40 04/07/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2013.1 (Build 6)
--

LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.std_logic_arith.ALL;

LIBRARY idx_fpga_lib;

ARCHITECTURE struct OF adc_v1_tb IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL Addr   : std_logic_vector(15 DOWNTO 0);
   SIGNAL CS_B   : std_logic;
   SIGNAL ExpAck : std_ulogic;
   SIGNAL ExpRd  : std_ulogic;
   SIGNAL ExpWr  : std_ulogic;
   SIGNAL F8M    : std_ulogic;
   SIGNAL MISO   : std_logic;
   SIGNAL RData  : std_logic_vector(15 DOWNTO 0);
   SIGNAL SCLK   : std_logic;
   SIGNAL rst    : std_logic;


   -- Component Declarations
   COMPONENT adc_v1
   GENERIC (
      BASE_ADDR : std_logic_vector := X"0E80"
   );
   PORT (
      Addr   : IN     std_logic_vector (15 DOWNTO 0);
      ExpRd  : IN     std_ulogic ;
      ExpWr  : IN     std_ulogic ;
      F8M    : IN     std_ulogic ;
      MISO   : IN     std_logic ;
      rst    : IN     std_logic ;
      CS_B   : OUT    std_logic ;
      ExpAck : OUT    std_ulogic ;
      RData  : OUT    std_logic_vector (15 DOWNTO 0);
      SCLK   : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT adc_v1_tester
   PORT (
      CS_B   : IN     std_logic ;
      ExpAck : IN     std_ulogic ;
      RData  : IN     std_logic_vector (15 DOWNTO 0);
      SCLK   : IN     std_logic ;
      Addr   : OUT    std_logic_vector (15 DOWNTO 0);
      ExpRd  : OUT    std_ulogic ;
      ExpWr  : OUT    std_ulogic ;
      F8M    : OUT    std_ulogic ;
      MISO   : OUT    std_logic ;
      rst    : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : adc_v1 USE ENTITY idx_fpga_lib.adc_v1;
   FOR ALL : adc_v1_tester USE ENTITY idx_fpga_lib.adc_v1_tester;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : adc_v1
      GENERIC MAP (
         BASE_ADDR => X"0E80"
      )
      PORT MAP (
         Addr   => Addr,
         ExpRd  => ExpRd,
         ExpWr  => ExpWr,
         F8M    => F8M,
         MISO   => MISO,
         rst    => rst,
         CS_B   => CS_B,
         ExpAck => ExpAck,
         RData  => RData,
         SCLK   => SCLK
      );
   U_1 : adc_v1_tester
      PORT MAP (
         CS_B   => CS_B,
         ExpAck => ExpAck,
         RData  => RData,
         SCLK   => SCLK,
         Addr   => Addr,
         ExpRd  => ExpRd,
         ExpWr  => ExpWr,
         F8M    => F8M,
         MISO   => MISO,
         rst    => rst
      );

END struct;
