-- VHDL Entity idx_fpga_lib.adc_int.symbol
--
-- Created:
--          by - nort.Domain Users (NORT-XPS14)
--          at - 11:35:11 05/02/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2013.1 (Build 6)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY adc_int IS
   GENERIC( 
      NBITSHIFT : integer          := 1;
      RATE_DEF  : std_logic_vector := "11111"
   );
   PORT( 
      ACQ       : IN     std_logic;
      ADD_EN    : IN     std_logic;
      CLK       : IN     std_ulogic;
      CLR       : IN     std_logic;
      MISO      : IN     std_logic;
      READ_EN   : IN     std_logic;
      STATUS_EN : IN     std_logic;
      rst       : IN     std_logic;
      CS_B      : OUT    std_logic;
      EOC       : OUT    std_logic;
      ERR       : OUT    std_logic;
      MOSI      : OUT    std_logic;
      SCLK      : OUT    std_logic;
      SINT      : OUT    std_logic_vector (31 DOWNTO 0)
   );

-- Declarations

END adc_int ;

--
-- VHDL Architecture idx_fpga_lib.adc_int.struct
--
-- Created:
--          by - nort.Domain Users (NORT-XPS14)
--          at - 11:35:10 05/02/14
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2013.1 (Build 6)
--

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY idx_fpga_lib;

ARCHITECTURE struct OF adc_int IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL INTENSITY : std_logic_vector(31 DOWNTO 0);

   -- Implicit buffer signal declarations
   SIGNAL ERR_internal : std_logic;


   -- Component Declarations
   COMPONENT adc_sm
   GENERIC (
      RATE_DEF : std_logic_vector(4 downto 0) := "01001"
   );
   PORT (
      ACQ       : IN     std_logic ;
      CLK       : IN     std_ulogic ;
      MISO      : IN     std_logic ;
      READ_EN   : IN     std_logic ;
      STATUS_EN : IN     std_logic ;
      rst       : IN     std_logic ;
      CS_B      : OUT    std_logic ;
      EOC       : OUT    std_logic ;
      ERR       : OUT    std_logic ;
      INTENSITY : OUT    std_logic_vector (31 DOWNTO 0);
      MOSI      : OUT    std_logic ;
      SCLK      : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT adc_summer
   GENERIC (
      NBITSHIFT : integer := 1
   );
   PORT (
      CLK       : IN     std_ulogic ;
      CLR       : IN     std_logic ;
      INTENSITY : IN     std_logic_vector (31 DOWNTO 0);
      rst       : IN     std_logic ;
      SINT      : OUT    std_logic_vector (31 DOWNTO 0);
      ADD_EN    : IN     std_logic ;
      ERR       : IN     std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : adc_sm USE ENTITY idx_fpga_lib.adc_sm;
   FOR ALL : adc_summer USE ENTITY idx_fpga_lib.adc_summer;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : adc_sm
      GENERIC MAP (
         RATE_DEF => RATE_DEF
      )
      PORT MAP (
         ACQ       => ACQ,
         CLK       => CLK,
         MISO      => MISO,
         READ_EN   => READ_EN,
         STATUS_EN => STATUS_EN,
         rst       => rst,
         CS_B      => CS_B,
         EOC       => EOC,
         ERR       => ERR_internal,
         INTENSITY => INTENSITY,
         MOSI      => MOSI,
         SCLK      => SCLK
      );
   U_1 : adc_summer
      GENERIC MAP (
         NBITSHIFT => NBITSHIFT
      )
      PORT MAP (
         CLK       => CLK,
         CLR       => CLR,
         INTENSITY => INTENSITY,
         rst       => rst,
         SINT      => SINT,
         ADD_EN    => ADD_EN,
         ERR       => ERR_internal
      );

   -- Implicit buffered output assignments
   ERR <= ERR_internal;

END struct;
