-- VHDL Entity idx_fpga_lib.ao.symbol
--
-- Created:
--          by - nort.UNKNOWN (NORT-NBX200T)
--          at - 14:21:20 02/ 2/2011
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2009.2 (Build 10)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY ao IS
   PORT( 
      Addr      : IN     std_logic_vector (15 DOWNTO 0);
      ExpRd     : IN     std_ulogic;
      ExpWr     : IN     std_ulogic;
      F66M      : IN     std_logic;
      F8M       : IN     std_ulogic;
      rst       : IN     std_ulogic;
      DA_CLR_B  : OUT    std_logic;
      DA_CS_B   : OUT    std_logic_vector (1 DOWNTO 0);
      DA_LDAC_B : OUT    std_logic;
      DA_SCK    : OUT    std_logic;
      DA_SDI    : OUT    std_logic;
      ExpAck    : OUT    std_ulogic;
      Data      : INOUT  std_logic_vector (15 DOWNTO 0)
   );

-- Declarations

END ao ;

--
-- VHDL Architecture idx_fpga_lib.ao.struct
--
-- Created:
--          by - nort.UNKNOWN (NORT-NBX200T)
--          at - 14:21:20 02/ 2/2011
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2009.2 (Build 10)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY idx_fpga_lib;

ARCHITECTURE struct OF ao IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL BdEn  : std_ulogic;
   SIGNAL RdEn  : std_ulogic;
   SIGNAL WrEn  : std_ulogic;
   SIGNAL iData : std_logic_vector(15 DOWNTO 0);


   -- Component Declarations
   COMPONENT ao_addr
   PORT (
      Addr : IN     std_logic_vector (15 DOWNTO 0);
      BdEn : OUT    std_ulogic 
   );
   END COMPONENT;
   COMPONENT ao_ram
   PORT (
      Addr  : IN     std_logic_vector (15 DOWNTO 0);
      F8M   : IN     std_ulogic ;
      RdEn  : IN     std_ulogic ;
      WrEn  : IN     std_ulogic ;
      rst   : IN     std_ulogic ;
      iData : INOUT  std_logic_vector (15 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT ao_sm
   PORT (
      Addr      : IN     std_logic_vector (15 DOWNTO 0);
      F66M      : IN     std_logic ;
      WrEn      : IN     std_ulogic ;
      iData     : IN     std_logic_vector (15 DOWNTO 0);
      rst       : IN     std_ulogic ;
      DA_CLR_B  : OUT    std_logic ;
      DA_CS_B   : OUT    std_logic_vector (1 DOWNTO 0);
      DA_LDAC_B : OUT    std_logic ;
      DA_SCK    : OUT    std_logic ;
      DA_SDI    : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT subbus_io
   PORT (
      BdEn   : IN     std_ulogic;
      ExpRd  : IN     std_ulogic;
      ExpWr  : IN     std_ulogic;
      F8M    : IN     std_ulogic;
      rst    : IN     std_ulogic;
      ExpAck : OUT    std_ulogic;
      RdEn   : OUT    std_ulogic;
      WrEn   : OUT    std_ulogic;
      Data   : INOUT  std_logic_vector (15 DOWNTO 0);
      iData  : INOUT  std_logic_vector (15 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : ao_addr USE ENTITY idx_fpga_lib.ao_addr;
   FOR ALL : ao_ram USE ENTITY idx_fpga_lib.ao_ram;
   FOR ALL : ao_sm USE ENTITY idx_fpga_lib.ao_sm;
   FOR ALL : subbus_io USE ENTITY idx_fpga_lib.subbus_io;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_1 : ao_addr
      PORT MAP (
         Addr => Addr,
         BdEn => BdEn
      );
   U_2 : ao_ram
      PORT MAP (
         Addr  => Addr,
         F8M   => F8M,
         RdEn  => RdEn,
         WrEn  => WrEn,
         rst   => rst,
         iData => iData
      );
   U_3 : ao_sm
      PORT MAP (
         Addr      => Addr,
         F66M      => F66M,
         WrEn      => WrEn,
         iData     => iData,
         rst       => rst,
         DA_CLR_B  => DA_CLR_B,
         DA_CS_B   => DA_CS_B,
         DA_LDAC_B => DA_LDAC_B,
         DA_SCK    => DA_SCK,
         DA_SDI    => DA_SDI
      );
   U_0 : subbus_io
      PORT MAP (
         Data   => Data,
         ExpRd  => ExpRd,
         ExpWr  => ExpWr,
         ExpAck => ExpAck,
         F8M    => F8M,
         rst    => rst,
         iData  => iData,
         RdEn   => RdEn,
         WrEn   => WrEn,
         BdEn   => BdEn
      );

END struct;
