-- VHDL Entity idx_fpga_lib.i2c_ext_switch.symbol
--
-- Created:
--          by - nort.UNKNOWN (NORT-NBX200T)
--          at - 14:38:43 11/23/2011
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2010.3 (Build 21)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_unsigned.all;

ENTITY i2c_ext_switch IS
   GENERIC( 
      N_SWBITS : integer                      := 8;
      I2C_ADDR : std_logic_vector(6 downto 0) := "1110000"
   );
   PORT( 
      clk   : IN     std_ulogic;
      rst   : IN     std_ulogic;
      scl   : IN     std_logic;
      m_scl : INOUT  std_logic_vector (N_SWBITS-1 DOWNTO 0);
      m_sda : INOUT  std_logic_vector (N_SWBITS-1 DOWNTO 0);
      sda   : INOUT  std_logic
   );

-- Declarations

END i2c_ext_switch ;

--
-- VHDL Architecture idx_fpga_lib.i2c_ext_switch.struct
--
-- Created:
--          by - nort.UNKNOWN (NORT-NBX200T)
--          at - 14:38:43 11/23/2011
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2010.3 (Build 21)
--
--  Copyright 2011 President and Fellows of Harvard College
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_unsigned.all;
USE ieee.std_logic_arith.all;

LIBRARY idx_fpga_lib;

ARCHITECTURE struct OF i2c_ext_switch IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL wdata : std_ulogic_vector(7 DOWNTO 0);


   -- Component Declarations
   COMPONENT i2c_half_switch
   GENERIC (
      N_ISBITS : integer range 20 downto 2 := 4
   );
   PORT (
      En       : IN     std_ulogic_vector (N_ISBITS-1 DOWNTO 0);
      pad_o    : IN     std_logic;
      padoen_o : IN     std_logic;
      pad_i    : OUT    std_logic;
      pad      : INOUT  std_logic_vector (N_ISBITS-1 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT i2c_slave
   GENERIC (
      I2C_ADDR : std_logic_vector(6 DOWNTO 0) := "1000000"
   );
   PORT (
      clk   : IN     std_ulogic ;
      rst   : IN     std_ulogic ;
      scl   : IN     std_logic ;
      wdata : OUT    std_ulogic_vector (7 DOWNTO 0);
      sda   : INOUT  std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : i2c_half_switch USE ENTITY idx_fpga_lib.i2c_half_switch;
   FOR ALL : i2c_slave USE ENTITY idx_fpga_lib.i2c_slave;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_1 : i2c_half_switch
      GENERIC MAP (
         N_ISBITS => N_SWBITS
      )
      PORT MAP (
         En       => wdata,
         pad_o    => sda,
         padoen_o => sda,
         pad_i    => sda,
         pad      => m_sda
      );
   U_2 : i2c_half_switch
      GENERIC MAP (
         N_ISBITS => N_SWBITS
      )
      PORT MAP (
         En       => wdata,
         pad_o    => scl,
         padoen_o => scl,
         pad_i    => OPEN,
         pad      => m_scl
      );
   U_0 : i2c_slave
      GENERIC MAP (
         I2C_ADDR => I2C_ADDR
      )
      PORT MAP (
         clk   => clk,
         rst   => rst,
         scl   => scl,
         wdata => wdata,
         sda   => sda
      );

END struct;
