-- VHDL Entity idx_fpga_lib.i2c_slave.symbol
--
-- Created:
--          by - nort.UNKNOWN (NORT-NBX200T)
--          at - 13:51:52 03/ 7/2011
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2009.2 (Build 10)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY i2c_slave IS
   GENERIC( 
      I2C_ADDR : std_logic_vector(6 DOWNTO 0) := "1000000"
   );
   PORT( 
      clk : IN     std_ulogic;
      rst : IN     std_ulogic;
      scl : IN     std_logic;
      sda : INOUT  std_logic
   );

-- Declarations

END i2c_slave ;

--
-- VHDL Architecture idx_fpga_lib.i2c_slave.struct
--
-- Created:
--          by - nort.UNKNOWN (NORT-NBX200T)
--          at - 13:51:52 03/ 7/2011
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2009.2 (Build 10)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY idx_fpga_lib;

ARCHITECTURE struct OF i2c_slave IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL err   : std_ulogic;
   SIGNAL start : std_ulogic;
   SIGNAL stop  : std_ulogic;


   -- Component Declarations
   COMPONENT i2c_slave_bits
   GENERIC (
      I2C_ADDR : std_logic_vector(6 downto 0) := "1000000"
   );
   PORT (
      clk   : IN     std_ulogic ;
      err   : IN     std_ulogic ;
      scl   : IN     std_logic ;
      start : IN     std_ulogic ;
      stop  : IN     std_ulogic ;
      sda   : INOUT  std_logic 
   );
   END COMPONENT;
   COMPONENT i2c_slave_sup
   PORT (
      clk    : IN     std_ulogic ;
      rst    : IN     std_ulogic ;
      scl_in : IN     std_logic ;
      sda_in : IN     std_logic ;
      err    : OUT    std_ulogic ;
      start  : OUT    std_ulogic ;
      stop   : OUT    std_ulogic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : i2c_slave_bits USE ENTITY idx_fpga_lib.i2c_slave_bits;
   FOR ALL : i2c_slave_sup USE ENTITY idx_fpga_lib.i2c_slave_sup;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : i2c_slave_bits
      GENERIC MAP (
         I2C_ADDR => I2C_ADDR
      )
      PORT MAP (
         clk   => clk,
         err   => err,
         scl   => scl,
         start => start,
         stop  => stop,
         sda   => sda
      );
   U_1 : i2c_slave_sup
      PORT MAP (
         clk    => clk,
         rst    => rst,
         scl_in => scl,
         sda_in => sda,
         err    => err,
         start  => start,
         stop   => stop
      );

END struct;
