-- VHDL Entity idx_fpga_lib.ptrh_i2c_sm.symbol
--
-- Created:
--          by - nort.UNKNOWN (NORT-NBX200T)
--          at - 13:16:26 02/15/2012
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2010.3 (Build 21)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
LIBRARY idx_fpga_lib;

ENTITY ptrh_i2c_sm IS
   GENERIC( 
      I2C_CLK_PRESCALE : std_logic_vector(15 DOWNTO 0) := X"000E"
   );
   PORT( 
      F8M       : IN     std_ulogic;
      Rd        : IN     std_logic;
      Rd3       : IN     std_logic;
      Wr        : IN     std_logic;
      WrStop    : IN     std_logic;
      i2c_addr  : IN     std_logic_vector (6 DOWNTO 0);
      i2c_wdata : IN     std_logic_vector (7 DOWNTO 0);
      rst       : IN     std_ulogic;
      wb_ack_o  : IN     std_logic;
      wb_dat_o  : IN     std_logic_vector (7 DOWNTO 0);
      wb_inta_o : IN     std_logic;
      Done      : OUT    std_logic;
      Err       : OUT    std_logic;
      i2c_rdata : OUT    std_logic_vector (23 DOWNTO 0);
      wb_adr_i  : OUT    std_logic_vector (2 DOWNTO 0);
      wb_cyc_i  : OUT    std_logic;
      wb_dat_i  : OUT    std_logic_vector (7 DOWNTO 0);
      wb_stb_i  : OUT    std_logic;
      wb_we_i   : OUT    std_logic
   );

-- Declarations

END ptrh_i2c_sm ;

--
-- VHDL Architecture idx_fpga_lib.ptrh_i2c_sm.fsm
--
-- Created:
--          by - nort.UNKNOWN (NORT-NBX200T)
--          at - 13:16:26 02/15/2012
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2010.3 (Build 21)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
LIBRARY idx_fpga_lib;
 
ARCHITECTURE fsm OF ptrh_i2c_sm IS

   -- Architecture Declarations
   SIGNAL Rd3_req : std_logic;  
   SIGNAL Rd_req : std_logic;  
   SIGNAL WrStop_req : std_logic;  
   SIGNAL Wr_req : std_logic;  

   TYPE STATE_TYPE IS (
      i2ci_0,
      i2ci_1,
      i2ci_2,
      i2ci_4,
      i2ci_5,
      i2ci_7,
      i2ci_8,
      i2c_10,
      w_10,
      w_11,
      w_12,
      w_13,
      w_14,
      w_16,
      w_17,
      r_10,
      r_11,
      r_13,
      r_14,
      r_15,
      r_16,
      r_18,
      r_20,
      r_21,
      r_23,
      r_25,
      r_27,
      r_28,
      r_30,
      r_31,
      r_32,
      w_24,
      i2c_1,
      w_9,
      w_3,
      w_25,
      w_6,
      w_26,
      w_15,
      w_27,
      w_18,
      w_28,
      w_6a1,
      w_29,
      w_30,
      w_31,
      w_32
   );
 
   -- Declare current and next state signals
   SIGNAL current_state : STATE_TYPE;
   SIGNAL next_state : STATE_TYPE;

   -- Declare Wait State internal signals
   SIGNAL csm_timer : std_logic_vector(18 DOWNTO 0);
   SIGNAL csm_next_timer : std_logic_vector(18 DOWNTO 0);
   SIGNAL csm_timeout : std_logic;
   SIGNAL csm_to_w_32 : std_logic;

   -- Declare any pre-registered internal signals
   SIGNAL Done_cld : std_logic ;
   SIGNAL Err_cld : std_logic ;
   SIGNAL i2c_rdata_cld : std_logic_vector (23 DOWNTO 0);
   SIGNAL wb_adr_i_cld : std_logic_vector (2 DOWNTO 0);
   SIGNAL wb_cyc_i_cld : std_logic ;
   SIGNAL wb_dat_i_cld : std_logic_vector (7 DOWNTO 0);
   SIGNAL wb_stb_i_cld : std_logic ;
   SIGNAL wb_we_i_cld : std_logic ;

BEGIN

   -----------------------------------------------------------------
   clocked_proc : PROCESS ( 
      F8M
   )
   -----------------------------------------------------------------
   BEGIN
      IF (F8M'EVENT AND F8M = '1') THEN
         IF (rst = '1') THEN
            current_state <= i2ci_0;
            csm_timer <= (OTHERS => '0');
            -- Default Reset Values
            Done_cld <= '0';
            Err_cld <= '0';
            i2c_rdata_cld <= (others => '0');
            wb_adr_i_cld <= (others => '0');
            wb_cyc_i_cld <= '0';
            wb_dat_i_cld <= (others => '0');
            wb_stb_i_cld <= '0';
            wb_we_i_cld <= '0';
            Rd3_req <= '0';
            Rd_req <= '0';
            WrStop_req <= '0';
            Wr_req <= '0';
         ELSE
            current_state <= next_state;
            csm_timer <= csm_next_timer;

            -- Combined Actions
            CASE current_state IS
               WHEN i2ci_0 => 
                  Done_cld <= '0' ;
                   Err_cld <= '0' ;
               WHEN i2ci_1 => 
                  wb_adr_i_cld <= "000";
                  wb_dat_i_cld <=
                    I2C_CLK_PRESCALE(7 DOWNTO 0);
                  wb_we_i_cld <= '1' ;
                  wb_cyc_i_cld <= '1' ;
                  wb_stb_i_cld <= '1' ;
                  IF (wb_ack_o = '1') THEN 
                     wb_cyc_i_cld <= '0' ;
                     wb_stb_i_cld <= '0' ;
                  END IF;
               WHEN i2ci_4 => 
                  wb_adr_i_cld <= "001";
                  wb_dat_i_cld <=
                    I2C_CLK_PRESCALE(15 DOWNTO 8);
                  wb_we_i_cld <= '1' ;
                  wb_cyc_i_cld <= '1' ;
                  wb_stb_i_cld <= '1' ;
                  IF (wb_ack_o = '1') THEN 
                     wb_cyc_i_cld <= '0' ;
                     wb_stb_i_cld <= '0' ;
                  END IF;
               WHEN i2ci_7 => 
                  wb_adr_i_cld <= "010";
                  wb_dat_i_cld <= X"C0";
                  wb_we_i_cld <= '1' ;
                  wb_cyc_i_cld <= '1' ;
                  wb_stb_i_cld <= '1' ;
                  IF (wb_ack_o = '1') THEN 
                     wb_cyc_i_cld <= '0' ;
                     wb_stb_i_cld <= '0' ;
                  END IF;
               WHEN i2ci_8 => 
                  Done_cld <= '1';
               WHEN w_10 => 
                  wb_adr_i_cld <= "011";
                  wb_dat_i_cld <= i2c_wdata ;
                  wb_we_i_cld <= '1' ;
                  wb_cyc_i_cld <= '1' ;
                  wb_stb_i_cld <= '1' ;
                  IF (wb_ack_o
                         = '1') THEN 
                     wb_cyc_i_cld <= '0' ;
                     wb_stb_i_cld <= '0' ;
                  END IF;
               WHEN w_12 => 
                  wb_adr_i_cld <= "100";
                  wb_dat_i_cld <= '0'
                     & WrStop_req
                     & "010001";
                  wb_we_i_cld <= '1' ;
                  wb_cyc_i_cld <= '1' ;
                  wb_stb_i_cld <= '1' ;
                  IF (wb_ack_o
                         = '1') THEN 
                     wb_cyc_i_cld <= '0' ;
                     wb_stb_i_cld <= '0' ;
                  END IF;
               WHEN w_16 => 
                  wb_adr_i_cld <= "100";
                  wb_we_i_cld <= '0' ;
                  wb_cyc_i_cld <= '1' ;
                  wb_stb_i_cld <= '1' ;
                  IF (wb_ack_o = '1' AND
                      wb_dat_o(7) = '0') THEN 
                     wb_cyc_i_cld <= '0' ;
                     wb_stb_i_cld <= '0' ;
                  ELSIF (wb_ack_o = '1' AND 
                         wb_dat_o(7) /= '0') THEN 
                     wb_cyc_i_cld <= '0' ;
                     wb_stb_i_cld <= '0' ;
                  END IF;
               WHEN w_17 => 
                  Done_cld <= '1';
               WHEN r_10 => 
                  wb_adr_i_cld <= "100";
                  wb_dat_i_cld <="00100001";
                  wb_we_i_cld <= '1';
                  wb_cyc_i_cld <= '1' ;
                  wb_stb_i_cld <= '1' ;
                  IF (wb_ack_o
                         = '1') THEN 
                     wb_cyc_i_cld <= '0' ;
                     wb_stb_i_cld <= '0' ;
                  END IF;
               WHEN r_14 => 
                  wb_adr_i_cld <= "011";
                  wb_we_i_cld <= '0';
                  wb_cyc_i_cld <= '1' ;
                  wb_stb_i_cld <= '1' ;
                  IF (wb_ack_o
                         = '1') THEN 
                     i2c_rdata_cld(23 DOWNTO 16)
                        <= wb_dat_o;
                     wb_cyc_i_cld <= '0' ;
                     wb_stb_i_cld <= '0' ;
                  END IF;
               WHEN r_15 => 
                  wb_adr_i_cld <= "100";
                  wb_dat_i_cld <="00100001";
                  wb_we_i_cld <= '1';
                  wb_cyc_i_cld <= '1' ;
                  wb_stb_i_cld <= '1' ;
                  IF (wb_ack_o
                         = '1') THEN 
                     wb_cyc_i_cld <= '0' ;
                     wb_stb_i_cld <= '0' ;
                  END IF;
               WHEN r_20 => 
                  wb_adr_i_cld <= "100";
                  wb_dat_i_cld <="01101001";
                  wb_we_i_cld <= '1';
                  wb_cyc_i_cld <= '1' ;
                  wb_stb_i_cld <= '1' ;
                  IF (wb_ack_o
                         = '1') THEN 
                     wb_cyc_i_cld <= '0' ;
                     wb_stb_i_cld <= '0' ;
                  END IF;
               WHEN r_27 => 
                  wb_adr_i_cld <= "011";
                  wb_we_i_cld <= '0';
                  wb_cyc_i_cld <= '1' ;
                  wb_stb_i_cld <= '1' ;
                  IF (wb_ack_o
                         = '1') THEN 
                     i2c_rdata_cld(15 DOWNTO 8)
                        <= wb_dat_o;
                     wb_cyc_i_cld <= '0' ;
                     wb_stb_i_cld <= '0' ;
                  END IF;
               WHEN r_30 => 
                  wb_adr_i_cld <= "011";
                  wb_we_i_cld <= '0';
                  wb_cyc_i_cld <= '1' ;
                  wb_stb_i_cld <= '1' ;
                  IF (wb_ack_o
                         = '1') THEN 
                     i2c_rdata_cld(7 DOWNTO 0)
                        <= wb_dat_o;
                     wb_cyc_i_cld <= '0' ;
                     wb_stb_i_cld <= '0' ;
                  END IF;
               WHEN r_32 => 
                  Done_cld <= '1';
               WHEN i2c_1 => 
                  Done_cld <= '0' ;
                  Err_cld <= '0';
                  Wr_req <= Wr;
                  Rd_req <= Rd;
                  WrStop_req <=
                    WrStop;
                  Rd3_req <= Rd3;
               WHEN w_9 => 
                  wb_adr_i_cld <= "100";
                  wb_we_i_cld <= '0' ;
                  wb_cyc_i_cld <= '1' ;
                  wb_stb_i_cld <= '1' ;
                  IF (wb_ack_o = '1' AND 
                      wb_dat_o(7) /= '0') THEN 
                     wb_cyc_i_cld <= '0' ;
                     wb_stb_i_cld <= '0' ;
                  ELSIF (wb_ack_o = '1' AND
                         wb_dat_o(7) = '0' AND
                         wb_dat_o(5) = '1') THEN 
                     wb_cyc_i_cld <= '0' ;
                     wb_stb_i_cld <= '0' ;
                  ELSIF (wb_ack_o = '1' AND
                         wb_dat_o(7) = '0') THEN 
                     wb_cyc_i_cld <= '0' ;
                     wb_stb_i_cld <= '0' ;
                  END IF;
               WHEN w_3 => 
                  wb_adr_i_cld <= "011";
                  wb_dat_i_cld <=
                      i2c_addr & Rd_req;
                  wb_we_i_cld <= '1' ;
                  wb_cyc_i_cld <= '1' ;
                  wb_stb_i_cld <= '1' ;
                  IF (wb_ack_o
                         = '1') THEN 
                     wb_cyc_i_cld <= '0' ;
                     wb_stb_i_cld <= '0' ;
                  END IF;
               WHEN w_26 => 
                  wb_adr_i_cld <= "100";
                  wb_dat_i_cld <= "01000001";
                  wb_we_i_cld <= '1' ;
                  wb_cyc_i_cld <= '1' ;
                  wb_stb_i_cld <= '1' ;
                  IF (wb_ack_o
                         = '1') THEN 
                     wb_cyc_i_cld <= '0' ;
                     wb_stb_i_cld <= '0' ;
                  END IF;
               WHEN w_15 => 
                  wb_adr_i_cld <= "100";
                  wb_dat_i_cld <= "10010001";
                  wb_we_i_cld <= '1' ;
                  wb_cyc_i_cld <= '1' ;
                  wb_stb_i_cld <= '1' ;
                  IF (wb_ack_o
                         = '1') THEN 
                     wb_cyc_i_cld <= '0' ;
                     wb_stb_i_cld <= '0' ;
                  END IF;
               WHEN w_29 => 
                  Err_cld <= '1';
               WHEN OTHERS =>
                  NULL;
            END CASE;
         END IF;
      END IF;
   END PROCESS clocked_proc;
 
   -----------------------------------------------------------------
   nextstate_proc : PROCESS ( 
      Err_cld,
      Rd,
      Rd3_req,
      Wr,
      WrStop_req,
      Wr_req,
      csm_timeout,
      current_state,
      wb_ack_o,
      wb_dat_o,
      wb_inta_o
   )
   -----------------------------------------------------------------
   BEGIN
      -- Default assignments to Wait State entry flags
      csm_to_w_32 <= '0';
      CASE current_state IS
         WHEN i2ci_0 => 
            next_state <= i2ci_1;
         WHEN i2ci_1 => 
            IF (wb_ack_o = '1') THEN 
               next_state <= i2ci_2;
            ELSE
               next_state <= i2ci_1;
            END IF;
         WHEN i2ci_2 => 
            IF (wb_ack_o = '0') THEN 
               next_state <= i2ci_4;
            ELSE
               next_state <= i2ci_2;
            END IF;
         WHEN i2ci_4 => 
            IF (wb_ack_o = '1') THEN 
               next_state <= i2ci_5;
            ELSE
               next_state <= i2ci_4;
            END IF;
         WHEN i2ci_5 => 
            IF (wb_ack_o = '0') THEN 
               next_state <= i2ci_7;
            ELSE
               next_state <= i2ci_5;
            END IF;
         WHEN i2ci_7 => 
            IF (wb_ack_o = '1') THEN 
               next_state <= i2ci_8;
            ELSE
               next_state <= i2ci_7;
            END IF;
         WHEN i2ci_8 => 
            IF (wb_ack_o = '0') THEN 
               next_state <= i2c_10;
            ELSE
               next_state <= i2ci_8;
            END IF;
         WHEN i2c_10 => 
            IF (Rd = '1' OR
                Wr = '1') THEN 
               next_state <= i2c_1;
            ELSE
               next_state <= i2c_10;
            END IF;
         WHEN w_10 => 
            IF (wb_ack_o
                   = '1') THEN 
               next_state <= w_11;
            ELSE
               next_state <= w_10;
            END IF;
         WHEN w_11 => 
            IF (wb_ack_o
                   = '0') THEN 
               next_state <= w_12;
            ELSE
               next_state <= w_11;
            END IF;
         WHEN w_12 => 
            IF (wb_ack_o
                   = '1') THEN 
               next_state <= w_13;
            ELSE
               next_state <= w_12;
            END IF;
         WHEN w_13 => 
            IF (wb_ack_o = '0' AND
                wb_inta_o = '0') THEN 
               next_state <= w_14;
            ELSE
               next_state <= w_13;
            END IF;
         WHEN w_14 => 
            IF (wb_inta_o = '1') THEN 
               next_state <= w_16;
            ELSE
               next_state <= w_14;
            END IF;
         WHEN w_16 => 
            IF (wb_ack_o = '1' AND
                wb_dat_o(7) = '0') THEN 
               next_state <= w_17;
            ELSIF (wb_ack_o = '1' AND 
                   wb_dat_o(7) /= '0') THEN 
               next_state <= w_24;
            ELSE
               next_state <= w_16;
            END IF;
         WHEN w_17 => 
            IF (wb_ack_o
                   = '0') THEN 
               next_state <= i2c_10;
            ELSE
               next_state <= w_17;
            END IF;
         WHEN r_10 => 
            IF (wb_ack_o
                   = '1') THEN 
               next_state <= r_11;
            ELSE
               next_state <= r_10;
            END IF;
         WHEN r_11 => 
            IF (wb_ack_o = '0' AND
                wb_inta_o = '0') THEN 
               next_state <= r_13;
            ELSE
               next_state <= r_11;
            END IF;
         WHEN r_13 => 
            IF (wb_inta_o = '1') THEN 
               next_state <= r_14;
            ELSE
               next_state <= r_13;
            END IF;
         WHEN r_14 => 
            IF (wb_ack_o
                   = '1') THEN 
               next_state <= r_25;
            ELSE
               next_state <= r_14;
            END IF;
         WHEN r_15 => 
            IF (wb_ack_o
                   = '1') THEN 
               next_state <= r_16;
            ELSE
               next_state <= r_15;
            END IF;
         WHEN r_16 => 
            IF (wb_ack_o = '0' AND
                wb_inta_o = '0') THEN 
               next_state <= r_18;
            ELSE
               next_state <= r_16;
            END IF;
         WHEN r_18 => 
            IF (wb_inta_o = '1') THEN 
               next_state <= r_27;
            ELSE
               next_state <= r_18;
            END IF;
         WHEN r_20 => 
            IF (wb_ack_o
                   = '1') THEN 
               next_state <= r_21;
            ELSE
               next_state <= r_20;
            END IF;
         WHEN r_21 => 
            IF (wb_ack_o = '0' AND
                wb_inta_o = '0') THEN 
               next_state <= r_23;
            ELSE
               next_state <= r_21;
            END IF;
         WHEN r_23 => 
            IF (wb_inta_o = '1') THEN 
               next_state <= r_30;
            ELSE
               next_state <= r_23;
            END IF;
         WHEN r_25 => 
            IF (wb_ack_o
                   = '0') THEN 
               next_state <= r_15;
            ELSE
               next_state <= r_25;
            END IF;
         WHEN r_27 => 
            IF (wb_ack_o
                   = '1') THEN 
               next_state <= r_28;
            ELSE
               next_state <= r_27;
            END IF;
         WHEN r_28 => 
            IF (wb_ack_o
                   = '0') THEN 
               next_state <= r_20;
            ELSE
               next_state <= r_28;
            END IF;
         WHEN r_30 => 
            IF (wb_ack_o
                   = '1') THEN 
               next_state <= r_31;
            ELSE
               next_state <= r_30;
            END IF;
         WHEN r_31 => 
            IF (wb_ack_o
                   = '0') THEN 
               next_state <= r_32;
            ELSE
               next_state <= r_31;
            END IF;
         WHEN r_32 => 
            next_state <= i2c_10;
         WHEN w_24 => 
            IF (WrStop_req = '1' AND
                wb_ack_o  = '0') THEN 
               next_state <= w_29;
            ELSIF (wb_ack_o
                      = '0') THEN 
               next_state <= w_26;
            ELSE
               next_state <= w_24;
            END IF;
         WHEN i2c_1 => 
            next_state <= w_3;
         WHEN w_9 => 
            IF (wb_ack_o = '1' AND 
                wb_dat_o(7) /= '0') THEN 
               next_state <= w_25;
            ELSIF (wb_ack_o = '1' AND
                   wb_dat_o(7) = '0' AND
                   wb_dat_o(5) = '1') THEN 
               next_state <= w_32;
               csm_to_w_32 <= '1';
            ELSIF (wb_ack_o = '1' AND
                   wb_dat_o(7) = '0') THEN 
               next_state <= w_30;
            ELSE
               next_state <= w_9;
            END IF;
         WHEN w_3 => 
            IF (wb_ack_o
                   = '1') THEN 
               next_state <= w_6;
            ELSE
               next_state <= w_3;
            END IF;
         WHEN w_25 => 
            IF (wb_ack_o
                   = '0') THEN 
               next_state <= w_26;
            ELSE
               next_state <= w_25;
            END IF;
         WHEN w_6 => 
            IF (wb_ack_o
                   = '0') THEN 
               next_state <= w_15;
            ELSE
               next_state <= w_6;
            END IF;
         WHEN w_26 => 
            IF (wb_ack_o
                   = '1') THEN 
               next_state <= w_27;
            ELSE
               next_state <= w_26;
            END IF;
         WHEN w_15 => 
            IF (wb_ack_o
                   = '1') THEN 
               next_state <= w_18;
            ELSE
               next_state <= w_15;
            END IF;
         WHEN w_27 => 
            IF (wb_ack_o = '0' AND
                wb_inta_o = '0') THEN 
               next_state <= w_28;
            ELSE
               next_state <= w_27;
            END IF;
         WHEN w_18 => 
            IF (wb_ack_o = '0' AND
                wb_inta_o = '0') THEN 
               next_state <= w_6a1;
            ELSE
               next_state <= w_18;
            END IF;
         WHEN w_28 => 
            IF (wb_inta_o
                  = '1') THEN 
               next_state <= w_29;
            ELSE
               next_state <= w_28;
            END IF;
         WHEN w_6a1 => 
            IF (wb_inta_o
                  = '1') THEN 
               next_state <= w_9;
            ELSE
               next_state <= w_6a1;
            END IF;
         WHEN w_29 => 
            next_state <= w_31;
         WHEN w_30 => 
            IF ((wb_ack_o
                   = '0') AND (Err_cld = '1')) THEN 
               next_state <= i2c_10;
            ELSIF ((wb_ack_o
                      = '0') AND (Wr_req = '1')) THEN 
               next_state <= w_10;
            ELSIF ((wb_ack_o
                      = '0') AND (Rd3_req = '1')) THEN 
               next_state <= r_10;
            ELSIF (wb_ack_o
                      = '0') THEN 
               next_state <= r_15;
            ELSE
               next_state <= w_30;
            END IF;
         WHEN w_31 => 
            IF (Err_cld = '1') THEN 
               next_state <= i2c_10;
            ELSIF (Wr_req = '1') THEN 
               next_state <= w_10;
            ELSIF (Rd3_req = '1') THEN 
               next_state <= r_10;
            ELSE
               next_state <= r_15;
            END IF;
         WHEN w_32 => 
            IF (csm_timeout = '1') THEN 
               next_state <= w_15;
            ELSE
               next_state <= w_32;
            END IF;
         WHEN OTHERS =>
            next_state <= i2ci_0;
      END CASE;
   END PROCESS nextstate_proc;
 
   -----------------------------------------------------------------
   csm_wait_combo_proc: PROCESS (
      csm_timer,
      csm_to_w_32
   )
   -----------------------------------------------------------------
   VARIABLE csm_temp_timeout : std_logic;
   BEGIN
      IF (unsigned(csm_timer) = 0) THEN
         csm_temp_timeout := '1';
      ELSE
         csm_temp_timeout := '0';
      END IF;

      IF (csm_to_w_32 = '1') THEN
         csm_next_timer <= "1001110000111111111"; -- no cycles(320000)-1=319999
      ELSE
         IF (csm_temp_timeout = '1') THEN
            csm_next_timer <= (OTHERS=>'0');
         ELSE
            csm_next_timer <= unsigned(csm_timer) - '1';
         END IF;
      END IF;
      csm_timeout <= csm_temp_timeout;
   END PROCESS csm_wait_combo_proc;

   -- Concurrent Statements
   -- Clocked output assignments
   Done <= Done_cld;
   Err <= Err_cld;
   i2c_rdata <= i2c_rdata_cld;
   wb_adr_i <= wb_adr_i_cld;
   wb_cyc_i <= wb_cyc_i_cld;
   wb_dat_i <= wb_dat_i_cld;
   wb_stb_i <= wb_stb_i_cld;
   wb_we_i <= wb_we_i_cld;
END fsm;
