-- VHDL Entity idx_fpga_lib.CtState.interface
--
-- Created:
--          by - nort.UNKNOWN (NORT-NBX200T)
--          at - 15:47:45 08/16/2010
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2009.2 (Build 10)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE ieee.std_logic_unsigned.all;
USE ieee.numeric_std.all;

ENTITY CtState IS
   PORT( 
      CtEn    : IN     std_ulogic;
      F8M     : IN     std_ulogic;
      PosEn   : IN     std_ulogic;
      RdEn    : IN     std_ulogic;
      StepClk : IN     std_ulogic;
      WrEn    : IN     std_ulogic;
      rst     : IN     std_logic;
      ClkEn   : OUT    std_ulogic;
      Ld      : OUT    std_ulogic
   );

-- Declarations

END CtState ;

--
-- VHDL Architecture idx_fpga_lib.CtState.struct
--
-- Created:
--          by - nort.UNKNOWN (NORT-NBX200T)
--          at - 15:47:45 08/16/2010
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2009.2 (Build 10)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
USE ieee.std_logic_unsigned.all;

LIBRARY idx_fpga_lib;

ARCHITECTURE struct OF CtState IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL R : std_ulogic;


   -- Component Declarations
   COMPONENT CtStB
   PORT (
      F8M     : IN     std_ulogic ;
      R       : IN     std_ulogic ;
      StepClk : IN     std_ulogic ;
      WrEn    : IN     std_ulogic ;
      rst     : IN     std_ulogic ;
      ClkEn   : OUT    std_ulogic 
   );
   END COMPONENT;
   COMPONENT CtStC
   PORT (
      CtEn  : IN     std_ulogic ;
      F8M   : IN     std_ulogic ;
      PosEn : IN     std_ulogic ;
      RdEn  : IN     std_ulogic ;
      WrEn  : IN     std_ulogic ;
      R     : OUT    std_ulogic ;
      Ld    : OUT    std_ulogic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : CtStB USE ENTITY idx_fpga_lib.CtStB;
   FOR ALL : CtStC USE ENTITY idx_fpga_lib.CtStC;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   CtStB1 : CtStB
      PORT MAP (
         F8M     => F8M,
         R       => R,
         StepClk => StepClk,
         WrEn    => WrEn,
         rst     => rst,
         ClkEn   => ClkEn
      );
   CtStC1 : CtStC
      PORT MAP (
         CtEn  => CtEn,
         F8M   => F8M,
         PosEn => PosEn,
         RdEn  => RdEn,
         WrEn  => WrEn,
         R     => R,
         Ld    => Ld
      );

END struct;
