function make_waves
% make_waves
% Read CPCI14/ssp.log and generate PT.mat and waves.m
F = load('CPCI14/ssp.log');
CPCI14 = F(:,2);
TPT = F(:,1);
CellP = ones(size(TPT)) * 40;
Tavg = ones(size(TPT)) * 25 + 273.15;

ws = [ F(:,5:7) F(:,8)+1 ]; % NCh NS NC NA
[B,I,J] = unique(ws,'rows');
QCLI_Wave = J-1;
save PT.mat TPT CellP Tavg CPCI14 QCLI_Wave

RR = 5e6; % RawRate (for now)
for i=1:size(B,1)
  WaveSpecs(i) = struct( ...
    'Name', sprintf('Wave_%d', i-1), ...
    'RawRate', RR, ...
    'RawSamples', B(i,2)*B(i,4), ...
    'NetSamples', B(i,2), ...
    'NAverage', B(i,4), ...
    'NCoadd', B(i,3), ...
    'FTrigger', RR/(B(i,2)*B(i,3)*B(i,4)), ...
    'ISICOS', 1, ...
    'TzSamples', 10, ...
    'dIdt', 0., ...
    'I0', 0. );
end
save WaveSpecs.mat WaveSpecs
fd = fopen('waves.m', 'w');
fprintf(fd, 'load WaveSpecs.mat\n' );
fclose(fd);
